Ganzfriend/tailwind scripts
headwayio/shipwright-tokens pull request #65
Opened 2023-02-23 19:24 UTC by Ganzfriend

Add comments describing the helper functions in `build.ts`.

Add logic to `build.ts` to replace spaces in keys with hyphens, and change `textCase` to `textTransform`. 

Fix small typo in `README`.

2023-02-24 16:22 UTC, spreston4 approved these changes
LGTM!

2023-02-28 16:18 UTC, panzacoder requested changes

2023-02-28 16:18 UTC, panzacoder commented on action-scripts/build.ts
> +    const { fontWeight, lineHeight, letterSpacing, textCase } = obj;
```suggestion
```

2023-02-28 17:12 UTC, panzacoder approved these changes
Looks great!

2023-02-28 17:14 UTC, merged